"""empty message

Revision ID: 4430a26303be
Revises: 46d8df49582a
Create Date: 2024-11-28 22:49:50.376571

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '4430a26303be'
down_revision = '46d8df49582a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
