"""empty message

Revision ID: 46d8df49582a
Revises: e220ff2a0047
Create Date: 2024-11-28 21:29:09.752812

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '46d8df49582a'
down_revision = 'e220ff2a0047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_products',
    sa.Column('dishid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishid'], ['my_app_schema.dishes.dishid'], ),
    sa.ForeignKeyConstraint(['productid'], ['my_app_schema.products.productid'], ),
    sa.PrimaryKeyConstraint('dishid', 'productid'),
    schema='my_app_schema'
    )
    op.alter_column('ordered_dishes', 'dishid',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='my_app_schema')
    op.alter_column('ordered_drinks', 'drinkid',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='my_app_schema')
    op.add_column('prices', sa.Column('priceid', sa.Integer(), nullable=False), schema='my_app_schema')
    op.add_column('prices', sa.Column('valid_from', sa.Date(), nullable=True), schema='my_app_schema')
    op.add_column('prices', sa.Column('valid_to', sa.Date(), nullable=True), schema='my_app_schema')
    op.add_column('prices', sa.Column('price_type', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True), schema='my_app_schema')
    op.create_foreign_key(None, 'prices', 'dishes', ['dishid'], ['dishid'], source_schema='my_app_schema', referent_schema='my_app_schema')
    op.drop_column('prices', 'count', schema='my_app_schema')
    op.drop_constraint('shelf_life_deliveryID_fkey', 'shelf_life', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key(None, 'shelf_life', 'product_in_delivery', ['shelflifeid', 'deliveryID'], ['productid', 'deliveryid'], source_schema='my_app_schema', referent_schema='my_app_schema')
    op.alter_column('staff', 'contact_info',
               existing_type=sa.INTEGER(),
               type_=sa.String().with_variant(sa.String(length=255), 'postgresql'),
               existing_nullable=True,
               schema='my_app_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'contact_info',
               existing_type=sa.String().with_variant(sa.String(length=255), 'postgresql'),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='my_app_schema')
    op.drop_constraint(None, 'shelf_life', schema='my_app_schema', type_='foreignkey')
    op.create_foreign_key('shelf_life_deliveryID_fkey', 'shelf_life', 'delivery', ['deliveryID'], ['deliveryid'], source_schema='my_app_schema', referent_schema='my_app_schema')
    op.add_column('prices', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True), schema='my_app_schema')
    op.drop_constraint(None, 'prices', schema='my_app_schema', type_='foreignkey')
    op.drop_column('prices', 'price_type', schema='my_app_schema')
    op.drop_column('prices', 'valid_to', schema='my_app_schema')
    op.drop_column('prices', 'valid_from', schema='my_app_schema')
    op.drop_column('prices', 'priceid', schema='my_app_schema')
    op.alter_column('ordered_drinks', 'drinkid',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='my_app_schema')
    op.alter_column('ordered_dishes', 'dishid',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='my_app_schema')
    op.drop_table('dish_products', schema='my_app_schema')
    # ### end Alembic commands ###
