"""empty message

Revision ID: ce749835cd2b
Revises: fcea042f0718
Create Date: 2024-11-20 17:25:04.073827

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'ce749835cd2b'
down_revision = 'fcea042f0718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('dishid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('recipe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dishid'),
    schema='my_app_schema'
    )
    op.create_table('drinks',
    sa.Column('drinkid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('drinkid'),
    schema='my_app_schema'
    )
    op.create_table('prices',
    sa.Column('dishid', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('dishid'),
    schema='my_app_schema'
    )
    op.create_table('products',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('productid'),
    schema='my_app_schema'
    )
    op.create_table('staff',
    sa.Column('staffid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('date_of_hire', sa.Date(), nullable=True),
    sa.Column('salary', sa.Numeric(), nullable=True),
    sa.Column('contact_info', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('staffid'),
    schema='my_app_schema'
    )
    op.create_table('suppliers',
    sa.Column('supplierid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('supplierid'),
    schema='my_app_schema'
    )
    op.create_table('tables',
    sa.Column('tableid', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tableid'),
    schema='my_app_schema'
    )
    op.create_table('delivery',
    sa.Column('deliveryid', sa.Integer(), nullable=False),
    sa.Column('datedelivery', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['deliveryid'], ['my_app_schema.suppliers.supplierid'], ),
    sa.PrimaryKeyConstraint('deliveryid'),
    schema='my_app_schema'
    )
    op.create_table('orders',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('tableid', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('total_sum', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('staffid', sa.Integer(), nullable=True),
    sa.Column('clientid', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['my_app_schema.clients.clientid'], ),
    sa.ForeignKeyConstraint(['staffid'], ['my_app_schema.staff.staffid'], ),
    sa.ForeignKeyConstraint(['tableid'], ['my_app_schema.tables.tableid'], ),
    sa.PrimaryKeyConstraint('orderid'),
    schema='my_app_schema'
    )
    op.create_table('ordered_dishes',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('dishid', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dishid'], ['my_app_schema.dishes.dishid'], ),
    sa.ForeignKeyConstraint(['orderid'], ['my_app_schema.orders.orderid'], ),
    sa.PrimaryKeyConstraint('orderid'),
    schema='my_app_schema'
    )
    op.create_table('ordered_drinks',
    sa.Column('orderid', sa.Integer(), nullable=False),
    sa.Column('drinkid', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drinkid'], ['my_app_schema.drinks.drinkid'], ),
    sa.ForeignKeyConstraint(['orderid'], ['my_app_schema.orders.orderid'], ),
    sa.PrimaryKeyConstraint('orderid'),
    schema='my_app_schema'
    )
    op.create_table('product_in_delivery',
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('deliveryid', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['deliveryid'], ['my_app_schema.delivery.deliveryid'], ),
    sa.ForeignKeyConstraint(['productid'], ['my_app_schema.products.productid'], ),
    sa.PrimaryKeyConstraint('productid', 'deliveryid'),
    schema='my_app_schema'
    )
    op.create_table('shelf_life',
    sa.Column('shelflifeid', sa.Integer(), nullable=False),
    sa.Column('expirationdate', sa.Date(), nullable=True),
    sa.Column('deliveryID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliveryID'], ['my_app_schema.delivery.deliveryid'], ),
    sa.PrimaryKeyConstraint('shelflifeid'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shelf_life', schema='my_app_schema')
    op.drop_table('product_in_delivery', schema='my_app_schema')
    op.drop_table('ordered_drinks', schema='my_app_schema')
    op.drop_table('ordered_dishes', schema='my_app_schema')
    op.drop_table('orders', schema='my_app_schema')
    op.drop_table('delivery', schema='my_app_schema')
    op.drop_table('tables', schema='my_app_schema')
    op.drop_table('suppliers', schema='my_app_schema')
    op.drop_table('staff', schema='my_app_schema')
    op.drop_table('products', schema='my_app_schema')
    op.drop_table('prices', schema='my_app_schema')
    op.drop_table('drinks', schema='my_app_schema')
    op.drop_table('dishes', schema='my_app_schema')
    # ### end Alembic commands ###
