"""Initial1

Revision ID: fcea042f0718
Revises: 
Create Date: 2024-11-20 17:13:08.349427

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = 'fcea042f0718'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('clientid'),
    schema='my_app_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients', schema='my_app_schema')
    # ### end Alembic commands ###
